version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "python"
max_line_length = 150

[analyzers.meta]
runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

[analyzers.meta]
plugins = ["react"]

[[analyzers]]
name = "docker"

[analyzers.meta]
dockerfile_paths = [
    "frontend/Dockerfile.dev",
    "frontend/Dockerfile.prod",
    "backend/Dockerfile.dev",
    "backend/Dockerfile.prod"
]

[[transformers]]
name = "prettier"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"
