repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: ^backend/
        args: [--config=backend/pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^backend/
        args: [--settings-path=backend/pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.23.0
    hooks:
      - id: eslint
        files: frontend/.*\.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx in frontend directory
        types: [file]
        args: [--config=frontend/eslint.config.js]
        additional_dependencies:
          - "eslint@9.23.0"
          - "@antfu/eslint-config@4.11.0"
