services:
  # Database: PostgreSQL database for testing
  db:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-backend_test}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 1s
      timeout: 1s
      retries: 50
    command: postgres -c shared_buffers=256MB -c max_connections=200

  # Test Runner: Service to run the tests
  test_runner:
    image: test_runner:latest
    command: pytest -v
    env_file: .env.test
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - ./frontend/pytest.ini:/app/pytest.ini

volumes:
  postgres_test_data:
