name: Build Frontend Image

on:
  workflow_run:
    workflows: ["Frontend Linting"]
    types:
      - completed
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-frontend:
    name: Build Frontend Image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: false
          load: true
          tags: stock-scanner-frontend:latest
          cache-from: type=gha,scope=frontend-prod
          cache-to: type=gha,mode=max,scope=frontend-prod
          build-args: |
            BUILDKIT_INLINE_CACHE=1
